Vagrant.require_version ">= 1.9.0"
Vagrant.configure(2) do |config|
  config.ssh.insert_key = false

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.verbose = "v"
  end
end
